### ISSUE TITLE
Main Process files

### ISSUE THREAD

**Issue by jadech32** [nateshmbhat/electron-react-ts-starter#1]
More of a question than an Issue, sorry.

Why does the main process have both js and ts files, and how is this starter repo different than https://github.com/Robinfr/electron-react-typescript ? Are there problems there that you have solved? 

Thank you.

**Comment by nateshmbhat** [comment]
The repo https://github.com/Robinfr/electron-react-typescript  is not created with Create-React-App and uses webpack configurations . Most react projects today are built with CRA and hence its not useful.
And btw , the index.js file is generated after compilations , i forgot to add to it .gitignore . will do it .
